### ISSUE TITLE
Can't use path_provider 1.0.0 

### ISSUE THREAD

**Issue by erf** [mchome/flutter_advanced_networkimage#100]
`Because flutter_advanced_networkimage >=0.4.5 depends on path_provider ^0.5.0 and ... depends on path_provider ^1.0.0, flutter_advanced_networkimage >=0.4.5 is forbidden.`

**Comment by erf** [comment]
Using  ^0.5.0-alpha.2 and flutter master

**Comment by mchome** [comment]
https://www.dartlang.org/tools/pub/dependencies#dependency-overrides

**Comment by erf** [comment]
That works - closing. Maybe add support for path_provider 1.0.0 later?
