### ISSUE TITLE
ZoomableList performance issue

### ISSUE THREAD

**Issue by karnadii** [mchome/flutter_advanced_networkimage#102]
I have > 100 file image in my storage, and when I display them all in ZoomableList, the app is force close.  the code is the same with #101

**Comment by mchome** [comment]
Will your app fc without `ZoomableList`?

**Comment by karnadii** [comment]
I use Listview.builder and https://github.com/YoussefKababe/pinch_zoom_image before and everything when smooth no fc, but when I change it with ZoomableList, everything is laggy.

**Comment by mchome** [comment]
ZoomableList use column to scale, so it is expected.
