### ISSUE TITLE
Flutter to upgrade error for StringBuffer

### ISSUE THREAD

**Issue by maxcong** [mchome/flutter_advanced_networkimage#105]
Compiler message:
    file:///Users/shuai/dev/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_advanced_networkimage-0.4.15/lib/src/flutter_advanced_networksvg.dart:106:29: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
     - 'StringBuffer' is from 'dart:core'.
     - 'Iterable' is from 'dart:core'.
     - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/shuai/dev/flutter/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
    Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
          informationCollector: (StringBuffer information) {
                                ^

**Comment by mchome** [comment]
Try 0.5.0-alpha.3.
