### ISSUE TITLE
path_provider issues

### ISSUE THREAD

**Issue by FilipeOS** [mchome/flutter_advanced_networkimage#109]
Hi, please update the dependencies.

`Because flutter_advanced_networkimage 0.4.15 depends on path_provider ^0.5.0 and no versions of flutter_advanced_networkimage match >0.4.15 <0.5.0, flutter_advanced_networkimage ^0.4.15 requires path_provider ^0.5.0.`

**Comment by mchome** [comment]
#100 https://www.dartlang.org/tools/pub/dependencies#dependency-overrides
