### ISSUE TITLE
How can I use an image that is already in cache?

### ISSUE THREAD

**Issue by juliosinaysantos** [mchome/flutter_advanced_networkimage#110]
Que tal,  tengo una aplicación de recetas que posee dos pantallas en la primera muestra la lista de recetas y cada una de ellas es un card con una imagen y el nombre, la segunda pantalla muestra los detalles de la receta seleccionada, incluyendo la imagen.

Mi problema es que cuando mando a traer la imagen en la pantalla de detalles esta la vuelve a traer de internet aunque ya haya sido cargada en el feed principal y se guarda en el cache de forma independiente aumentando el tamaño de la app.

**Comment by marianoarga** [comment]
@juliosinaysantos no utilices español en un plugin donde el lenguaje principal es ingles jaja

**Comment by marianoarga** [comment]
Proba si esta relacionado con este issue, necesitas saber donde esta la imagen ya cacheada
https://github.com/mchome/flutter_advanced_networkimage/issues/38#issuecomment-459762945
