### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by aeoriwnd** [mchome/flutter_advanced_networkimage#116]
Hello, when building an iOS project I have this error message:

file:///Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_advanced_networkimage-0.3.14/lib/flutter_advanced_networkimage.dart:87:29: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.

Does the package need an upgrade?

**Comment by mchome** [comment]
Please use `v0.5.0`.
