### ISSUE TITLE
Function to call when clicked on refresh

### ISSUE THREAD

**Issue by sulaysumaria** [mchome/flutter_advanced_networkimage#117]
This is a feature request. I want to call a function when the refresh button is pressed.

What works now is when clicked on refresh button, it simply tries to reload the URL.

Thoughts?

**Comment by sulaysumaria** [comment]
@AlaaEldeenYsr , Good to have that feature... But it doesn't fit my usecase...

I have uploaded image to AWS S3 and to get image from there, I need to generate a pre signed url that expires in maximum 7 days... So if the url returns error, I want to generate a new url and use it to fetch the image, again it will last for 7 days, but after that I will need to regenerate it...

So if there is a function available that has to return a url, it will be easier...

If you have any other alternatives to achieve this, please suggest... One thing to note, I cannot make the bucket public, so that's not an option...

**Comment by AlaaEldeenYsr** [comment]
I think you can use this package in your case this
https://pub.dev/packages/flutter_image#-readme-tab-

And here is an example of how you can handle you customization.
[image: image.png]

Or you can create your own fetch strategy like this.
[image: image.png]

Or you can handle it in a raw way like this.
[image: image.png]

**Comment by sulaysumaria** [comment]
I think it does not provide caching...

I found another workaround though, setting the cacheTimeOut to a larger timespan did the trick...

So the URL is expired, but still it is in cache so image loads fine.
