### ISSUE TITLE
Problem loading URLs from Firebase Storage

### ISSUE THREAD

**Issue by Skquark** [mchome/flutter_advanced_networkimage#12]
I'm trying to load images that I uploaded to Firebase Storage and generated image URL from it, and it does not appear.  They worked fine with the builtin Network Image provider, but when I substituted with the AdvancedNetworkImage it doesn't show up.  I suspect it has something to do with the extra text in the image path and not parsing correctly.  Here is an example of the address that is used:
"https://firebasestorage.googleapis.com/v0/b/kquarum.appspot.com/o/discussions%2Fimage5677.jpg?alt=media&token=cbae2a27-65ce-4caf-bed3-b73323fe4dac"

Maybe it has to do with the %2F or the tags after the question mark, but it works when I put in a normal image path.  Pretty sure it's a bug that other people are going to be running across.  Thanks for this addon, was a needed one.

**Comment by mchome** [comment]
Ummm, the link works on my phone, perhaps it's a big file that need more time to load it.
The default timeout is 5 seconds, you can pass `timeoutDuration: Duration(minutes: 1)` in `AdvancedNetworkImage` class.

**Comment by Skquark** [comment]
Ah good, that was it, it was a 5mb jpg uploaded from phone camera and was failing loading because it takes too long to download.  I thought the timeout would have been to start the download waiting for server response, not for the max time for a load to finish.  Thanks for that setting.
I guess my next steps would be to resize the resolution of image after it's selected to be more manageable, then to animate the smaller TransitionToImage when tapped to go into full screen with your ZoomableImage.. Thanks for your help, looking good.
