### ISSUE TITLE
Feature Request - Check for image in asset bundle before going to network or fallback images

### ISSUE THREAD

**Issue by TheBogueRat** [mchome/flutter_advanced_networkimage#125]
Edited to add usage example...

WHAT:  I would like to pull from the asset bundle first if the image is available, then try the network location.

WHY:  I have a set of stock images to use for a weekend performance in my assets/ folder but I still need the option to pull from the network.  Rather than set up an elaborate versioning system, I'd like to check the assets folder for the image, before trying to grab it from the network by using this package which I already employ.  This was the simplest solution I could come up with.

SOLUTION:  Modify class AdvancedNetworkImage in src/provider/flutter_advanced_networkimage.dart as shown below.  I tried to fork so I could send a pull request but my fork doesn't match what I was getting via 'packages get' (0.5.0)  

```
class AdvancedNetworkImage extends ImageProvider<AdvancedNetworkImage> {
  AdvancedNetworkImage(
  this.url, {
  this.firstTryLocalAsset: '',

// .... AND ....

  final String firstTryLocalAsset;
  ```
  ```
  Future<ui.Codec> _loadAsync(AdvancedNetworkImage key) async {
  assert(key == this);

  String uId = uid(key.url);
...
  // Check to see if the image is available in the asset bundle before trying the network.
  if (key.firstTryLocalAsset!=null) {
    ByteData imageData = await rootBundle.load(key.firstTryLocalAsset).catchError((e) {});
    if (imageData != null) {
      return await PaintingBinding.instance.instantiateImageCodec(imageData.buffer.asUint8List());
    }
  }
...
  if (useDiskCache) {
  try {
  ```

Usage: 
```
image: AdvancedNetworkImage(
  performer.photo,
  firstTryLocalAsset: 'assets/performers/' + photoName,
  useDiskCache: true,
  fallbackAssetImage: 'assets/performers/image_not_avail.png',
),
```

**Comment by mchome** [comment]
It is not a common usage, so I am going to close this.
