### ISSUE TITLE
Advice on Zoomable widget issues

### ISSUE THREAD

**Issue by davbaron** [mchome/flutter_advanced_networkimage#126]
I have a couple of questions in regards to using the zoomable widget. Let's say I have a 'product' and that product can have multiple photos attached to it. I let the user see 'small' images on the 'product info' screen, however I then allow them to click on any small image which takes them to another screen where I show them a zoomable (full screen) version of the image.  In the app bar for that screen I have 'next' and 'previous' buttons so they can step through all of the images for the current product.  Assuming the user 'zooms in' on the initial image...  

Question 1:  If they click the 'next image' button, it displays the next image at the same (current) zoom level (and position) of the prior image.  Is there a way to 'reset' the zoomable widget to the initial  (default) zoom and position offset so that the 'next' image starts fully fitted?   

Question 2:  Other apps, such as Facebook, allows users to 'swipe' between images. This is only possible though if the user 'un-zooms' (double-click behavior) an image before swiping to the next or previous image.  I know I already have the next/previous buttons, but the swiping thing is more expected on a mobile device.  Is there a notion (enhancement) of providing an onSwipe property, and having the widget call that IF and ONLY IF the zoom and pan matched the 'initial' settings?  If not, are there any suggestions on how this might be do-able?

Thanks again for a great package of functionality...

**Comment by autolainen** [comment]
Recently I had the same problem as in Question 2 - I put ZoomableWidget in TabBarView and when image is zoomed in the horizontal swype gesture handlers of the widgets clashed. So instead of pan of the image I got switching tabs behaviour. So to solve that I replaced the part in _ZoomableWidgetState where GestureDetector is initialized:

```
        LayoutId(
          id: _ZoomableWidgetLayout.gestureContainer,
          child: GestureDetector(
            child: Container(color: Color(0)),
            onScaleStart: _onScaleStart,
            onScaleUpdate: _onScaleUpdate,
            onScaleEnd: widget.bounceBackBoundary ? _onScaleEnd : null,
            onDoubleTap: _handleDoubleTap,
            onTap: widget.onTap,
          ),
        ),

```
with RawGestureDetector:
```
        LayoutId(
          id: _ZoomableWidgetLayout.gestureContainer,
          child: RawGestureDetector(
            child: Container(color: Color(0)),
            gestures: <Type, GestureRecognizerFactory>{
              CustomScaleGestureRecognizer:
                  GestureRecognizerFactoryWithHandlers<
                          CustomScaleGestureRecognizer>(
                      () => CustomScaleGestureRecognizer(
                        onScaleStart: _onScaleStart,
                        onScaleUpdate: _onScaleUpdate,
                        onScaleEnd: widget.bounceBackBoundary ? _onScaleEnd : null,
                      ),
                      (CustomScaleGestureRecognizer instance) {
                instance.zoom = _zoom;
              })
            },
          ),
        ),
```
In CustomScaleGestureRecognizer implementation I put a condition on zoom factor. If the image is not zoomed - let TabBarView handle swype gesture or possibly do scaling. If image is zoomed in - we can do only scale or pan.
```
class CustomScaleGestureRecognizer extends ScaleGestureRecognizer {
  double zoom;

  CustomScaleGestureRecognizer(
      {GestureScaleStartCallback onScaleStart,
      GestureScaleUpdateCallback onScaleUpdate,
      GestureScaleEndCallback onScaleEnd}) {
    onStart = (ScaleStartDetails details) {
      onScaleStart(details);
    };
    onUpdate = (ScaleUpdateDetails details) {
      onScaleUpdate(details);
    };
    onEnd = (ScaleEndDetails details) {
      onScaleEnd(details);
    };
  }

  @override
  void addAllowedPointer(PointerEvent event) {
    super.addAllowedPointer(event);
    if (zoom != 1.0) {
      resolve(GestureDisposition.accepted);
    }
  }

  @override
  String get debugDescription => 'customScale';
}
```
Hope that will help in ZoomableWidget development.

**Comment by davbaron** [comment]
Thanks @autolainen , for that response - I see what you're doing and it makes sense.  In the mean time, I found another Flutter add-in, "photo_view", which in many ways is similar to zoomableWidget.  That said, the package also includes what I was really looking for: a 'gallery' (pageview) in which each image can be zoomed in, panned, etc.., just like eBay, FaceBook, etc...  In fact, unlike most other 'commercial' solutions to this issue that I've seen, the photo_view_gallery will actually swipe to the next image in the pageView even if the current image is zoomed in.  Every other implementation of this forces the user to reset the image to 'fit' mode before it will swipe forward or backward.  

I'm going to close this, I guess, thought I do think that what you've (@autolainen ) done might want to make it into the final code someday.
