### ISSUE TITLE
Flutter v1.12.2: Error: The method 'AdvancedNetworkImage.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.

### ISSUE THREAD

**Issue by Ivaskuu** [mchome/flutter_advanced_networkimage#127]
Error:
```
[+15740 ms] [+16243 ms]
[   +4 ms]             Compiler message:
[   +1 ms] [   +2 ms]
../../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_advanced_networkimage-0.5.0/lib/src/provider/flutt
er_advanced_networkimage.dart:143:24: Error: The method 'AdvancedNetworkImage.load' has fewer positional arguments than
those of overridden method 'ImageProvider.load'.
[   +4 ms] [        ]   ImageStreamCompleter load(AdvancedNetworkImage key) {
[   +3 ms] [        ]                        ^
[   +1 ms] [        ] /C:/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the
overridden method ('load').
[   +3 ms] [        ]   ImageStreamCompleter load(T key, DecoderCallback decode);
[   +3 ms] [        ]
```

The updated overriden method:
```
@protected
  ImageStreamCompleter load(T key, DecoderCallback decode);
```

Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.12.2, on Microsoft Windows [Versione 10.0.18362.476], locale it-IT)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[!] Android Studio (version 3.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.40.1)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by mchome** [comment]
Try `0.6.0-alpha.1`.

**Comment by sulaysumaria** [comment]
Can we keep this issue open until it is released?

**Comment by amreniouinnovent** [comment]
@mchome 0.6.0-alpha didn't fix the issue
check it here
`Target dart2js failed: Exception: ../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24:
Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../../Development/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24:
Info: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Error: Compilation failed.

`

![Screen Shot 2019-12-12 at 4 03 19 PM](https://user-images.githubusercontent.com/52191652/70710591-ed7bc480-1cf8-11ea-8d36-ff59948754ad.png)

**Comment by xxx102** [comment]
我也是报相同的错误，但是用 @protected
  ImageStreamCompleter load(T key, DecoderCallback decode);替代了@override
  ImageStreamCompleter load(AdvancedNetworkImage key) {
    return MultiFrameImageStreamCompleter(
      codec: _loadAsync(key),
      scale: key.scale,
      informationCollector: () sync* {
        yield DiagnosticsProperty<ImageProvider>('Image provider', this);
        yield DiagnosticsProperty<AdvancedNetworkImage>('Image key', key);
      },
    );
  }这个方法还是报错。请问各位大佬有什么解决方法
