### ISSUE TITLE
loadingWidgetBuilder does not work as shown in the docs

### ISSUE THREAD

**Issue by Atulin** [mchome/flutter_advanced_networkimage#128]
The documentation shows an example implementation of
```dart
loadingWidgetBuilder: (double progress) => Text(progress.toString()),
```
Meanwhile, on version `^0.5.0`, using such construction throws an error
```
error: The argument type 'Text Function(double)' can't be assigned to the parameter type 'Widget Function(BuildContext, double, Uint8List)'. (argument_type_not_assignable
```

**Comment by mchome** [comment]
Sorry, I forget to update the docs.

Use `loadingWidgetBuilder: (BuildContext context, double progress, Uint8List data) => Text(progress.toString()),`
or just `loadingWidgetBuilder: (_, double progress, __) => Text(progress.toString()),`
