### ISSUE TITLE
Overrriding issue between two different dart files

### ISSUE THREAD

**Issue by naresh3599** [mchome/flutter_advanced_networkimage#132]
I'm using the Advance Network Image package in my flutter project. While Compiling and running. I get the below error. 

`/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_advanced_networkimage-0.5.0/lib/src/provider/flutter_advanced_networkimage.dart:143:24: Error: The method 'AdvancedNetworkImage.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'. `
` ImageStreamCompleter load(AdvancedNetworkImage key) {
                       ^                                                                   `
`/C:/src/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^`
`Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.`

`FAILURE: Build failed with an exception. `

**Comment by mchome** [comment]
Use `0.6.0-alpha.1`.
