### ISSUE TITLE
0.6.0 Error: Type 'DecoderCallback' not found.

### ISSUE THREAD

**Issue by grandleaf** [mchome/flutter_advanced_networkimage#134]
0.5.0 is OK.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.40.2)
[✓] Connected device (1 available)

Compiler message:
../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_advanced_networkimage-0.6.0/lib/src/provider/flutter_advanced_networkimage.dart:159:55: Error: Type 'DecoderCallback' not found.
  ImageStreamCompleter load(AdvancedNetworkImage key, DecoderCallback decode) {
                                                      ^^^^^^^^^^^^^^^
../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_advanced_networkimage-0.6.0/lib/src/provider/flutter_advanced_networkimage.dart:171:33: Error: Type 'DecoderCallback' not found.
      AdvancedNetworkImage key, DecoderCallback decode) async {
                                ^^^^^^^^^^^^^^^
../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_advanced_networkimage-0.6.0/lib/src/provider/flutter_advanced_networkimage.dart:159:24: Error: The method 'AdvancedNetworkImage.load' has more required arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(AdvancedNetworkImage key, DecoderCallback decode) {
                       ^
../../Development/flutter/packages/flutter/lib/src/painting/image_provider.dart:383:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key);
                       ^
../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_advanced_networkimage-0.6.0/lib/src/provider/flutter_advanced_networkimage.dart:159:55: Error: 'DecoderCallback' isn't a type.
  ImageStreamCompleter load(AdvancedNetworkImage key, DecoderCallback decode) {
                                                      ^^^^^^^^^^^^^^^
../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_advanced_networkimage-0.6.0/lib/src/provider/flutter_advanced_networkimage.dart:171:33: Error: 'DecoderCallback' isn't a type.
      AdvancedNetworkImage key, DecoderCallback decode) async {
                                ^^^^^^^^^^^^^^^
Compiler failed on /Users/grandleaf/flutter/xreader/lib/main.dart

FAILURE: Build failed with an exception.
* Where:
Script '/Users/grandleaf/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugArm64'.
> Process 'command '/Users/grandleaf/Development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by mchome** [comment]
Sorry, I forget to level up the sdk version in `0.6.0`.
If you are using flutter 1.9.x, please hardcode `0.5.0`.

**Comment by smoj** [comment]
> Sorry, I forget to level up the sdk version in `0.6.0`.
> If you are using flutter 1.9.x, please hardcode `0.5.0`.

Lifesaver.
