### ISSUE TITLE
Option to commit the cache immediatly with AdvancedNetworkImage

### ISSUE THREAD

**Issue by ivanjpg** [mchome/flutter_advanced_networkimage#137]
If you use directly the `DiskCache().save(...)` the image is available immediatly to retrieve from cache using the _UID_;

When using `AdvancedNetworkImage(...)` with `cacheDisk: true` and later want to retrieve the image, the plugin downloads it again, unless _10_ operations are pending and then writes (I think) metadata stuff.

In `DiskCache.save(...)` function the _sync_ is accomplished using `_commitMetaData(true)`. Is there a way to tell `AdvancedNetworkImage(...)` to commit this changes immediatly?

**Comment by mchome** [comment]
Hey, @ivanjpg. AdvancedNetworkImage with cacheRule will use the DiskCache().save, otherwise the file will be save in `${getTemporaryDirectory().path}/imagecache/$uid`.

**Comment by ivanjpg** [comment]
I miss that part. Thanks a lot for the point it out and for your amazing work in this plugin!
