### ISSUE TITLE
request: Add image fit option to the  TransitionToImage

### ISSUE THREAD

**Issue by vazad28** [mchome/flutter_advanced_networkimage#14]
Like the tile says, I would appreciate the addition of the option to allow the option of BoxFit.

This allows the page to have square thumbnail in the page with gallery page.

Thanks
Before
<img width="375" alt="screen shot 2018-07-06 at 5 11 24 pm" src="https://user-images.githubusercontent.com/4810909/42402320-a2f4c0c0-813f-11e8-9cb4-b77a82ec6ecf.png">

After
<img width="375" alt="screen shot 2018-07-06 at 5 10 58 pm" src="https://user-images.githubusercontent.com/4810909/42402323-a983742c-813f-11e8-8bae-b0e3a00e9fc0.png">

**Comment by mchome** [comment]
It's on `0.2.10` now :)
