### ISSUE TITLE
[Feature Request] Load "optional" thumbnail image first

### ISSUE THREAD

**Issue by EricPreventa** [mchome/flutter_advanced_networkimage#141]
Any interest in adding the option for a thumbnail image to display first similar to this?
https://github.com/InvincibleZeal/progressive_image

I would use the above mentioned package, but it doesn't do caching, which is also what I want. I'm looking to load in a much lower quality image first to display to the user, before it downloads and updates to the much higher quality image.

I have very high resolution images that on some slow internet connections, takes a while for them to load and is creating (on some phones) a questionable experience.

**Comment by mchome** [comment]
Well, you can do it by nesting `TransitionToImage` widget.

**Comment by EricPreventa** [comment]
@mchome that seems like it would work, however for some reason doing

`TransitionToImage(placeholder: Image(image: AdvancedNetworkImage(url)),image: AdvancedNetworkImage(url))`

doesn't show the placeholder. It's black and just loads the image.

**Comment by mchome** [comment]
It is `loadingWidget`.
