### ISSUE TITLE
Overflow on channel when used with flutter web

### ISSUE THREAD

**Issue by fatimahossny** [mchome/flutter_advanced_networkimage#144]
I am trying to use this plugin with flutter web , it works fine without` useDiskCache` .
when I use` useDiskCache` with true it shows just circular loading with error in console of chrome

` Overflow on channel: plugins.flutter.io/path_provider.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.`

I used this code to save images before loading

```
  void initState() {
    super.initState();
    Future.delayed(Duration(seconds: 2), () async {
      for (int i = 0; i < images.length; i++) {
        precacheImage(
            AdvancedNetworkImage(
              images[i].url,
              useDiskCache: true,
              fallbackAssetImage: dummyUrl,
              cacheRule: CacheRule(
                storeDirectory: StoreDirectoryType.temporary,
                maxAge: const Duration(days: 7),
              ),
            ),
            context);
      }
    });
  }
```

and used  `TransitionToImage` the same as example with ` useDiskCache: true,`

am I missing anything ?
any help regarding this is very appreciated

**Comment by mchome** [comment]
`path_provider` did not support flutter web atm, see https://github.com/flutter/flutter/issues/45296.
Browsers have their own cache, I'll make a web solution.

**Comment by fatimahossny** [comment]
@mchome , I appreciate that , thanks

**Comment by mrjumpy** [comment]
same here +1

**Comment by mchome** [comment]
Hey guys, you can try commit `f330288db6d0cadf87e53d9eb0ceb396740911a0`.

**Comment by b-cancel** [comment]
@mchome are you using the browser's cache now when using flutter web?

**Comment by mchome** [comment]
> @mchome are you using the browser's cache now when using flutter web?

Yes.
