### ISSUE TITLE
gpu memory error and black screen appears after open and close big images repeatedly 

### ISSUE THREAD

**Issue by mojanimator** [mchome/flutter_advanced_networkimage#145]
hi.
i write a wallpaper application with flutter. it shows thumb images in grid view and when click on one image, the main big image download, and cache with advance network image. but when close this page and repeat clicking and closing, memory increases and a black screen appear on-page.
when i scroll on gridview, memory decreases but on clicking one or two images repeatedly, memory increases! i use the last version of the master channel
this is the link to my app.
http://www.qr-image-creator.com/app-release.apk

**Comment by mojanimator** [comment]
these are error reports

2020-02-13 21:03:24.647 25863-25863/? A/DEBUG: pid: 24094, tid: 24116, name: 1.gpu >>> com.varta.fashion_wallpapers <<<
2020-02-13 21:03:24.795 25863-25863/? A/DEBUG: #7 pc 000000000045b734 /data/app/com.varta.fashion_wallpapers-2/lib/arm64/libflutter.so (offset 0x280000)
2020-02-13 21:03:24.795 25863-25863/? A/DEBUG: #8 pc 000000000045f4bc /data/app/com.varta.fashion_wallpapers-2/lib/arm64/libflutter.so (offset 0x280000)
2020-02-13 21:03:24.795 25863-25863/? A/DEBUG: #9 pc 00000000003d6fc0 /data/app/com.varta.fashion_wallpapers-2/lib/arm64/libflutter.so (offset 0x280000)
2020-02-13 21:03:24.795 25863-25863/? A/DEBUG: #10 pc 00000000003d6af0

**Comment by mojanimator** [comment]
W/Adreno-GSL(12160): <sharedmem_gpuobj_alloc:2021>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL(12160): <gsl_memory_alloc_pure:2125>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
W/Adreno-GSL(12160): <sharedmem_gpuobj_alloc:2021>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL(12160): <gsl_memory_alloc_pure:2125>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
W/Adreno-GSL(12160): <sharedmem_gpuobj_alloc:2021>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL(12160): <gsl_memory_alloc_pure:2125>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
W/Adreno-GSL(12160): <sharedmem_gpuobj_alloc:2021>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL(12160): <gsl_memory_alloc_pure:2125>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
W/Adreno-GSL(12160): <sharedmem_gpuobj_alloc:2021>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL(12160): <gsl_memory_alloc_pure:2125>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
W/Adreno-GSL(12160): <sharedmem_gpuobj_alloc:2021>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL(12160): <gsl_memory_alloc_pure:2125>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
W/Adreno-GSL(12160): <sharedmem_gpuobj_alloc:2021>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL(12160): <gsl_memory_alloc_pure:2125>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
F/libc (12160): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xbc2609b0 in tid 12182 (1.gpu)
Lost connection to device.

**Comment by mchome** [comment]
Set width and height in `AdvancedNetworkImage`.

**Comment by mojanimator** [comment]
> Set width and height in `AdvancedNetworkImage`.

but images are not evenly sized and on a different device, sizes may be out of the screen

**Comment by mchome** [comment]
Please provide a minimum example to this issue.

**Comment by mojanimator** [comment]
> Please provide a minimum example to this issue.

[New video.zip](https://github.com/mchome/flutter_advanced_networkimage/files/4208429/New.video.zip)
this is a video scenario and minimal code.
in homepage i have a gridview that shows thumb images (not any problem with these) and when click on an image, wallpaperdetails widget appears and main big image downloaded and showed in view . after click on one image and closing it repeatedly, memory increases and black screen appears.

**Comment by mchome** [comment]
Looks like it is upstream issue.
