### ISSUE TITLE
Is there any way i can completely remove caching?

### ISSUE THREAD

**Issue by Jayant-BL** [mchome/flutter_advanced_networkimage#149]
I want to show user avatar and do not want any caching because when user change profile it seamlessly changes to new image however if user Pull to refresh to update profile data for a blip of sec previous image shows up. it's not a major issue but not a good UX for my app.

can this package solve this I've tried to implement it but still having the same issue?
I'm using the Cached_network_image package right now.

**Comment by mchome** [comment]
Ram cache: https://github.com/mchome/flutter_advanced_networkimage/issues/146
Rom cache: removeFromCache(url)
