### ISSUE TITLE
why  create Minimum image for for Uint8List?

### ISSUE THREAD

**Issue by hasonguo** [mchome/flutter_advanced_networkimage#15]
Uint8List _minimumImage = Uint8List.fromList([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,1,0,0,0,1,8,2,0,0,0,144,119,83,222,0,0,0,1,115,82,71,66,0,174,206,28,233,0,0,0,4,103,65,77,65,0,0,177,143,11,252,97,5,0,0,0,9,112,72,89,115,0,0,14,195,0,0,14,195,1,199,111,168,100,0,0,0,12,73,68,65,84,24,87,99,248,255,255,63,0,5,254,2,254,167,53,129,132,0,0,0,0,73,69,78,68,174,66,96,130]);

yes，I understand that you do this things for solve the exception of image loading.
But ,I Think This is not the best way to do it.Because sometimes I have  a image  of “1x1”(widthxheight).
Do you have the best way to do it

**Comment by mchome** [comment]
Hey, you can do this by parsing your image to Uint8List, then pass your custom Uint8List to `fallbackImageBytes` in `flutter_advanced_networkimage`.
