### ISSUE TITLE
Needing upgrade of flutter_svg dependancy

### ISSUE THREAD

**Issue by Skquark** [mchome/flutter_advanced_networkimage#150]
After latest update of the Flutter dev channel, it broke something with flutter_svg: ^0.17.1 and couldn't build.  I investigated and found they fixed the issue in the latest version, so I changed it in my local .pub-cache folder in your yaml to flutter_svg: ^0.17.3+1 and it works again.  Might be a good idea to bump that change in your next release.. Thanks.

**Comment by mchome** [comment]
You just need to run `flutter packages upgrade` because of `^`.
