### ISSUE TITLE
When navigation page is popped - image state reverts to loading

### ISSUE THREAD

**Issue by richgoldmd** [mchome/flutter_advanced_networkimage#18]
Regarding the dev branch (0.3.0) - 
I noticed if I used TransitionToImage on a page, pushed a new page onto the stack, and popped the new page back off, that the TransitionToImage showed the loading widget instead of the image, indefinitely.

I found that the method _TransitionToImageState._getImage() was resetting the status even if it didn't need to reload the image, leaving the state in the loading status indefinitely.

The updated method looks like this: (original code commented out for clarity)
```
  _getImage() {
    setState(() {
      _loadFailed = false;
    });
    final ImageStream oldImageStream = _imageStream;
    // This was resetting the status even if the image hadn't changed
    // _status = _TransitionStatus.loading;
    _imageStream =
        _imageProvider.resolve(createLocalImageConfiguration(context));
    if (_imageStream.key != oldImageStream?.key) {
      _status = _TransitionStatus.loading;
      oldImageStream?.removeListener(_updateImage);
      _imageStream.addListener(_updateImage);
    }
  }
```
This change solved the problem - when the new page was popped off the stack, the existing image displays correctly.

I didn't clone the repo so consider this a change request without the associated PR.

Thanks for a great package!

-Rich

**Comment by mchome** [comment]
https://github.com/mchome/flutter_advanced_networkimage/blob/3cb1e2aef2f803519c2c0fcaca0bcd42ce1ef9c8/lib/transition_to_image.dart#L233-L247
It should be good now, thank you for reporting this.

**Comment by richgoldmd** [comment]
No problem. Thanks for some great widgets.
