### ISSUE TITLE
Panning with 1 finger

### ISSUE THREAD

**Issue by modulovalue** [mchome/flutter_advanced_networkimage#20]
Could you add an option to make a `ZoomableWidget` pannable with 1 finger? This is the way the stock iOS Photos app does it (i.e. being able to pan with 1 and with 2 fingers)

P.S. Thanks for the great library! This is really the best one compared to other flutter alternatives.

**Comment by mchome** [comment]
`singleFingerPan` and `multiFingersPan` was added!

**Comment by modulovalue** [comment]
Thank you very much!
