### ISSUE TITLE
flutter_advanced_networkimage: ^0.3.3

### ISSUE THREAD

**Issue by galinowski** [mchome/flutter_advanced_networkimage#23]
Hi, I'm not really sure who needs to fix this but I have something to share below.

I'm stuck with version 0.2.11 if I put in pubspec.yaml: `flutter_advanced_networkimage: any`

If I set it to: `flutter_advanced_networkimage: ^0.3.3` I then get:

...development/flutter/bin/flutter --no-color packages get
Running "flutter packages get" in...
Because every version of flutter_test from sdk depends on quiver 0.29.0+1 and flutter_advanced_networkimage 0.3.3 depends on quiver ^2.0.0, flutter_test from sdk is incompatible with flutter_advanced_networkimage 0.3.3.
And because no versions of flutter_advanced_networkimage match >0.3.3 <0.4.0, flutter_test from sdk is incompatible with flutter_advanced_networkimage ^0.3.3.
So, because ... depends on both flutter_advanced_networkimage ^0.3.3 and flutter_test any from sdk, version solving failed.
pub get failed (1)
Process finished with exit code 1

To have the latest version 0.3.3, I add the following to pubspec.yaml:

```
dependency_overrides:
    quiver: ^0.29.0
```

**Comment by mchome** [comment]
Hi @galinowski, flutter upgraded some packages in trunk. As #19 mentioned, the quiver dependency was up to `2.0.0+1`. 
You can edit the `pubspeac.yaml` temporarily.
