### ISSUE TITLE
Double tap behavior

### ISSUE THREAD

**Issue by skybur** [mchome/flutter_advanced_networkimage#25]
Hello,

Would it be possible to change double tap behavior of `ZoomableWidget` from centering the image to:
1. If scale is 1.0, zoom step by step (e.g 0.5x each double tap) until hits max scale
2. If max scale, zoom out to scale 1.0 & center the image

Thank you.

**Comment by mchome** [comment]
It's done in `v0.3.4` :)

**Comment by skybur** [comment]
Wow it's very nice. Thank you very much 🙏 
I'm gonna close this then 😄
