### ISSUE TITLE
retryLimit can't be 0

### ISSUE THREAD

**Issue by p30arena** [mchome/flutter_advanced_networkimage#33]
TransitionToImage _loadFailed is not set to true when the url is empty

**Comment by p30arena** [comment]
this line doesn't work correctly:
if (ListEquality().equals(data.buffer.asUint8List(), featureImage))

**Comment by p30arena** [comment]
or maybe its an Emulator BUG, checking tomorrow

**Comment by mchome** [comment]
`TransitionToImage` displays error widget when `AdvancedNetworkImage` url get empty string on my device.

**Comment by p30arena** [comment]
I'm using DiskCache
it seems that retryLimit can't be 0
why not assert it?

**Comment by p30arena** [comment]
https://github.com/mchome/flutter_advanced_networkimage/pull/35

**Comment by p30arena** [comment]
the real problem is that although the image failed to load, **_loadFailed did not become true in TransitionToImage**

**Comment by mchome** [comment]
I dont have this problem and retryLimt is designed to be any integer.

**Comment by p30arena** [comment]
@mchome I've tested it and you are wrong, try it on a fresh app with no disk/memory cache,
set the retryLimit to 0,
no image will load

**Comment by p30arena** [comment]
_response = await retry(() async {

here you call retry, line 179

for (int t = 0; t < retryLimit; t++) {

on line 167

0 is not less than 0 so it will never run

please reconsider your design!

**Comment by mchome** [comment]
ok, i tested the example in hot-reload mode so it doesnt hint the network request in the 2nd time.
