### ISSUE TITLE
Quiver version

### ISSUE THREAD

**Issue by marianoarga** [mchome/flutter_advanced_networkimage#37]
Getting this message when trying to get packages:

> Because every version of flutter_test from sdk depends on quiver 0.29.0+1 and flutter_advanced_networkimage >=0.3.0 depends on quiver ^2.0.0, flutter_test from sdk is incompatible with flutter_advanced_networkimage >=0.3.0.
> So, because memes_de_superheroes depends on both flutter_advanced_networkimage ^0.3.6 and flutter_test any from sdk, version solving failed.
> pub get failed (1)

**Comment by mchome** [comment]
You need to upgrade flutter to the latest release version.

**Comment by marianoarga** [comment]
flutter --no-color upgrade
> Upgrading Flutter from /home/mariano/development/flutter...
> From https://github.com/flutter/flutter
>    809721d..3a3bab9  master     -> origin/master
> Already up-to-date.
> 
> Upgrading engine...
> Already up-to-date.
> 
> Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
> Framework • revision c7ea3ca377 (3 months ago) • 2018-05-29 21:07:33 +0200
> Engine • revision 1ed25ca7b7
> Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

**Comment by mchome** [comment]
Related to https://github.com/mchome/flutter_advanced_networkimage/issues/23.
Try the dev channel.

**Comment by marianoarga** [comment]
Yep, moving to dev channel works, thank you sir.
