### ISSUE TITLE
Image local path

### ISSUE THREAD

**Issue by marianoarga** [mchome/flutter_advanced_networkimage#38]
How can I get the cached image local path?
I would like to share the image once downloaded.
Ex:
> AdvancedNetworkImage image = AdvancedNetworkImage(IMAGE_URL);
> print(image.localPath);

**Comment by mchome** [comment]
Added in `v0.3.7`:)
```
print(await image.cachedPath);
```

**Comment by marianoarga** [comment]
Thanks a lot

**Comment by JotaFerreira** [comment]
@mchome how to do this in v0.4.0?

**Comment by mchome** [comment]
```dart
File(join((await getTemporaryDirectory()).path, 'imagecache', url.hashCode.toString()));
```

**Comment by JotaFerreira** [comment]
Thanks a lot
