### ISSUE TITLE
TransitionToImage BoxFit.cover behaves like BoxFit.contain

### ISSUE THREAD

**Issue by richgoldmd** [mchome/flutter_advanced_networkimage#41]
The title says it all. If I have an image in a constrained container nested in a TransitionToImage() instance, the image appears as if the BoxFit was set to BoxFit.contain.

Maybe because the ANI image is wrapped in Center() ???

**Comment by richgoldmd** [comment]
I just updated my app to use the latest version and this issue has reappeared.
I note in the code that Center() has reappeared in TransitionToImage - I belive this is breaking the Boxfit option.

**Comment by mchome** [comment]
My bad, try `v0.3.11`.

**Comment by richgoldmd** [comment]
Fixed!
Thanks again for a fantastic plugin and quick follow-up!
