### ISSUE TITLE
Add bordershapes/clipping

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [mchome/flutter_advanced_networkimage#45]
It would be nice to make it a circle directly inside the widget. I'm trying to use this with a `CircleAvatar` and it works as the child, but the child of the `CircleAvatar`doesn't get clipped into the circle, only the backround image does. The backgroundImage of the `CircleAvatar` takes an Imageprovider, but then the TransitionToImage doesn't work... So, long story short, it would be nice if we could tell it to be a circle

**Comment by mchome** [comment]
Hi, you can try to wrap `TransitionToImage` in [ClipRRect](https://docs.flutter.io/flutter/widgets/ClipRRect-class.html)(borderRadius: BorderRadius.circular(10000.0), child: ...).

**Comment by ThinkDigitalRepair** [comment]
Thank you for this! I'll check it out.

**Comment by ThinkDigitalRepair** [comment]
That’s perfect. It worked, thank you! It would still be a nice user friendly feature, but not necessary

**Comment by mchome** [comment]
Added in `0.4.0`.
