### ISSUE TITLE
how to set maxAge in cacheConfig

### ISSUE THREAD

**Issue by opensourcegps** [mchome/flutter_advanced_networkimage#47]
How to control how long images are stored in cache?

Is something similar to this possible:
https://pub.dartlang.org/packages/flutter_cache_manager

```
CacheManager.maxAgeCacheObject = new Duration(days: 30);
```

**Comment by mchome** [comment]
No, loading cache files depend on their filenames in this version. But it will be controllable in 0.4.x.
