### ISSUE TITLE
Zoom state

### ISSUE THREAD

**Issue by dasmikko** [mchome/flutter_advanced_networkimage#48]
Would it be possible to have a `onZoomStateChanged` method, for then the user is zooming, or the image is back at original zoom state.

I need it to disable pageView scroll if the image is zoomed, to prevent pageview scrolling.

**Comment by mchome** [comment]
Try version `0.3.12`, sample code:
```dart
onZoomStateChanged: (double zoom) {
  print(zoom);
},
```

**Comment by dasmikko** [comment]
Awesome, it works! 

Thanks for the super quick response.
