### ISSUE TITLE
minScale and maxScale don't work

### ISSUE THREAD

**Issue by romaluca** [mchome/flutter_advanced_networkimage#5]
hi i'm try your plugin.
I use this code:

```
new Scaffold(
      body: new ZoomableWidget(
        minScale: 0.8,
        maxScale: 1.6,
        child: new Center(
          child: new Image(
              image: new AdvancedNetworkImage(
                url)),
        ),
      ),
```

but the minScale and maxScale don't work

**Comment by mchome** [comment]
Hi @romaluca, the minScale and maxScale are limiting your scale size. Did your Center component over scale the mixScale value or maxScale? Or, the ZoomableWidget just dont scale?  
If you only zoom a single picture, i would recommend you to use https://pub.dartlang.org/packages/zoomable_image.

**Comment by romaluca** [comment]
Sorry but i didn't set the package well. 
now it works but when i zoom it the animation is no good.
I prefer this plugin because it has minscale and maxscale

Thanks

**Comment by mchome** [comment]
Yes, it's bad. I will create a new widget like https://pub.dartlang.org/packages/zoomable_image  with minscale and maxscale next version.

**Comment by mchome** [comment]
I've made some tweaks for the old widget, it should be better :)

**Comment by romaluca** [comment]
Hi, i just tried the new version of your plugin. 
The first time that i zoom an image it works well 
But with the image zoomed if i try to zoom in/out it, the animation is no good.

Thanks!

**Comment by mchome** [comment]
Hi, @romaluca . What's the plugin version which you are using? It's `0.2.0` and work ok in example. You can provide me a example or gif.

**Comment by romaluca** [comment]
Sorry i didn't use TranstionToImage like example! now it is very better.
The last bit issue is when i zoom out, the image don't return to the center of screen

Thanks for your work!

**Comment by mchome** [comment]
For now you can double tap the screen to center the image :)
