### ISSUE TITLE
gif was in slow motion in TransitionToImage widget

### ISSUE THREAD

**Issue by JotaFerreira** [mchome/flutter_advanced_networkimage#53]
I tried using gifs, but the gif was in slowmotion.

**Comment by mchome** [comment]
Try https://github.com/mchome/flutter_advanced_networkimage/commit/54c0c940b94af735cc865e6ad3f17d2e5ff015c5 with this setup:
https://www.dartlang.org/tools/pub/dependencies#git-packages
