### ISSUE TITLE
TransitionToImage with Hero Animation?

### ISSUE THREAD

**Issue by shoxter** [mchome/flutter_advanced_networkimage#54]
It seems that the image flashes a few times when transitioning routes and wrapping the TransitionToImage in a Hero widget. This problem doesn't exist when using the default Image.network constructor. Is anyone else having this issue? Is there something specific I'm missing?

I thought that it may be trying to refetch the image, but I'm using the disk's cache so I'm not sure where to go.

Thanks!

**Comment by mchome** [comment]
Hi, did this also happened in flutter's [FadeInImage](https://docs.flutter.io/flutter/widgets/FadeInImage-class.html) widget?

**Comment by shoxter** [comment]
I'm actually looking into that now. I'll post my findings.

**Comment by shoxter** [comment]
It doesn't appear to. I used FadeInImage alongside the transparent_image package and it works without issue.

**Comment by mchome** [comment]
Try `0.4.0-alpha`, it's better upgrade to flutter v1.1.7.

**Comment by mchome** [comment]
`0.4.0` fixed this.
