### ISSUE TITLE
Target of URI doesn't exist:  provider.dart & transition.dart

### ISSUE THREAD

**Issue by hicham-alsayed-ahmad** [mchome/flutter_advanced_networkimage#56]
i cant get those 2 files at flutter_advanced_networkimage and i tried to change 
`D:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.407], locale en-US)
    • Flutter version 1.0.0 at D:\flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Hecham\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Hecham\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.30.2)
    • VS Code at C:\Users\Hecham\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.22.3

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0`
`D:\flutter\bin\flutter.bat --no-color upgrade
Upgrading Flutter from D:\flutter...
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (9 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.407], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.30.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0`
when i run android 

> Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  D:\flutter_app\Review Apps\foodapp-master\foodapp-master\lib\src\ui\card_widget.dart
...refers, in an import, to the following library:
  D:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_advanced_networkimage-0.3.13\lib\provider.dart
Unfortunately, that library does not appear to exist on your file system.

screenshot 
[https://imgur.com/a/Xgw5Dtu](url)

**Comment by mchome** [comment]
`0.4.0` version require flutter: ">=1.1.7 <2.0.0".
For flutter 1.0.0 developers, refer https://github.com/mchome/flutter_advanced_networkimage/tree/c1c69046e1974d88feba35deb59adbed3b39b105

**Comment by hicham-alsayed-ahmad** [comment]
thanks for your reply , i change it now and i got one new error . 
`D:\flutter\bin\flutter.bat --no-color packages upgrade
Running "flutter packages upgrade" in foodapp-master...         
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because foodapp requires SDK version >=1.1.7 <2.0.0, version solving failed.

pub upgrade failed (1)
Process finished with exit code 1`

**Comment by mchome** [comment]
Hi, if you want to use `0.4.0`, you need to switch your flutter channel to dev.
