### ISSUE TITLE
Feature request: Flinging support

### ISSUE THREAD

**Issue by dasmikko** [mchome/flutter_advanced_networkimage#61]
Would it be possible to have fling support? 

Like when you are panning, the image continues to pan for a moment.

Just like the Google Photos app.

**Comment by mchome** [comment]
Hi @dasmikko, you can try commit `be20aa224ccdd065549a1686f6da5ea73e342b80`.

**Comment by dasmikko** [comment]
How to I make the pubspec file point to that commit?

**Comment by dasmikko** [comment]
Nevermind, found out. Testing it now.

**Comment by dasmikko** [comment]
Works perfectly! Thanks for the awesome work.

**Comment by mchome** [comment]
Now in `0.4.7` :)
