### ISSUE TITLE
path_provider dependency problem

### ISSUE THREAD

**Issue by sjmcdowall** [mchome/flutter_advanced_networkimage#62]
With the latest upgrade to flutter packages -- we are getting a conflict that flutter_advaned_networkimage required path_provider 0.4.X but the latest is 0.5.X.  Please increment the dependencies so this works again?  Thanks!

Actually I submitted a PR #63 to fix this issue.

**Comment by mchome** [comment]
Done.

**Comment by sjmcdowall** [comment]
Hey @mchome -- I may have been a wee bit too "nice" -- I am thinking that the version should go to 0.5.0 for the path_provider change because that change is a breaking change ..  Thoughts?

**Comment by mchome** [comment]
I havent migrate my app to androidx, but get no compile error.

**Comment by sjmcdowall** [comment]
Ok .. I tried and it was a horrible night mare but not due to this granted ..

Just thought better safe than sorry .. ☺️
