### ISSUE TITLE
Unsure how to use fallbackImage or maybe bug with fallbackImage

### ISSUE THREAD

**Issue by davbaron** [mchome/flutter_advanced_networkimage#64]
Hello, I am relatively new to Flutter (several months now) and am hoping to use the AdvancedNetworkImage in place of the delivered NetworkImage. My first attempt to do so is not working.  

Within my widget tree, I want to use a delivered CircleAvatar as the 'leading' for a series of listView ListTiles (photos of people).  Here is the code for that:
`CircleAvatar(backgroundImage: netImg, radius: 25.0, backgroundColor: Colors.deepPurple,)`

The newImg var is declared within the Widget build() code (since it will be used in a list of 'people'.  Here is the code for that:
`AdvancedNetworkImage netImg = AdvancedNetworkImage(
      _photoPath,
      loadFailedCallback: () => print('Oh, no!!!'),
      fallbackImage: unknownAvatarBytes,
) ;`

If the image *is* found, it works great.  If the image is missing, then I want the 'fallbackImage' to display instead. At first I thought the fallbackImage was in fact, and 'image', but it is not. I'm wondering why you didn't make the type of that an actual image, versus a Uint8List (which I had never used before). I would think that fallback images are essentially a 'constant' and would be a 'local' image file, or in my case, an Asset file. In any case, after doing some research on the web, I found what I believe to be a way to set the fallbackImage value. Assuming I have a state variable of type Uint8List, named 'unknownAvatarBytes', here is my code that I run during the page's initState:

`void initState() {
    
    super.initState();

    rootBundle.load('assets/unknown_avatar.png').then((data) {
    if (mounted)
        setState(() {
          unknownAvatarBytes = data.buffer.asUint8List();
        });
    });
}`

The problem is that when the remote image is missing, instead of my 'asset image' showing up, all I get is an empty white circle. I have debugged the initState code, and after the Uint8List var is assigned into, the number of bytes matches the 'size' of the image file on disk, so I *think* that part is working.  Unfortunately I see no fallback image.  

If I am approaching this wrong, please tell me so, otherwise any recommendations or insights would be appreciated.

Thank you!

**Comment by mchome** [comment]
Hi, can the `unknownAvatarBytes` works in `Image.memory(unknownAvatarBytes)`?

**Comment by mchome** [comment]
Try this:
```dart
unknownAvatarBytes != null
  ? CircleAvatar(
      backgroundImage: AdvancedNetworkImage(
        'error url',
        fallbackImage: unknownAvatarBytes,
      ),
      backgroundColor: Colors.deepPurple,
    )
  : SizedBox(),
```
I can add fallbackAssetImage(String) option if you like.
