### ISSUE TITLE
ZoomableList with listview

### ISSUE THREAD

**Issue by karnadii** [mchome/flutter_advanced_networkimage#65]
Is there is a way to make a zoomable image list in listview? i need the controller to scroll smoothly, i cant control the scroll using column

**Comment by mchome** [comment]
Hi, do you want the fling animation in zoomablelist? It's a todo in https://github.com/mchome/flutter_advanced_networkimage/issues/61.
If not, feel free to reopen.

**Comment by mchome** [comment]
Now in `0.4.7` :)
