### ISSUE TITLE
fallback widget on error

### ISSUE THREAD

**Issue by erf** [mchome/flutter_advanced_networkimage#69]
I experienced an exception was thrown in the `AdvancedNetworkImage._loadAsync`, when an image failed to load. Would it be possible to add a fallback widget for these cases? ( Instead of an image )

**Comment by carmas123** [comment]
Can be a good think also have a widget for preloading (or an image assets) to display before load image.

**Comment by erf** [comment]
@mchome does setting `TransitionToImage.Placeholder` avoid the exception if the image fails to load?

**Comment by mchome** [comment]
Sure, you can reload the image in `TransitionToImage` too :)

**Comment by carmas123** [comment]
Yes sorry for my request I use this lib from 2 days :)
