### ISSUE TITLE
Future already completed

### ISSUE THREAD

**Issue by andreidiaconu** [mchome/flutter_advanced_networkimage#73]
Hi! Some of the images in our app are not loading all the way and when this happens, I also see an error in the logs:

```
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
#1      loadFromRemote.<anonymous closure>.<anonymous closure> (package:flutter_advanced_networkimage/src/flutter_advanced_networkimage.dart:387:19)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#5      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#6      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#7      _HandlerEventSink.add (dart:async/stream_transformers.dart:238:13)
#8      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_imp<…>
```

I am using version 0.4.8 and the previous version, 0.3.9 did not have this issue. I will be downgrading to see which version last worked properly.

This image never loads all the way to the end https://postmuse-app.firebaseapp.com/previews/-LXxjk9oS9TxFPUQi8j_.jpg

**Comment by andreidiaconu** [comment]
You can see the issue reproduce in the Android version of the app: https://play.google.com/store/apps/details?id=com.postmuseapp.designer

**Comment by mchome** [comment]
Hi @andreidiaconu , try commit `8996f19855ba4fcabac8730479bf7a8cd3a0e97b`. It should be fixed.

**Comment by mchome** [comment]
`v0.4.9` released.

**Comment by andreidiaconu** [comment]
@mchome Thank you for fixing this and sorry for the late reply. I think I was experiencing 2 issues: the one described in this ticket, which made some of the images not load and an undiagnosed issue that prevents just the picture I linked above to fail to load.

 In other words, I no longer see the error in my logs and most of my images are loading just fine, but https://postmuse-app.firebaseapp.com/previews/-LXxjk9oS9TxFPUQi8j_.jpg is still not loading properly. It looks like this (worked with 0.3.9).

![screenshot 2019-03-02 at 00 16 43](https://user-images.githubusercontent.com/1402046/53669658-84065a00-3c80-11e9-92ea-07c032a379f0.png)

**Comment by andreidiaconu** [comment]
Let me know if I can help diagnose this and if you want this in a separate ticket.

**Comment by andreidiaconu** [comment]
Nevermind. I now see it must have been a cached version of the file on my machine. My apologies and thank you again.
