### ISSUE TITLE
update flutter_svg dependency version

### ISSUE THREAD

**Issue by jinfagang** [mchome/flutter_advanced_networkimage#76]
As for this [issue](https://github.com/dnfield/flutter_svg/issues/106) the flutter_svg has build error actually with version 10.2, should update to 10.3.

I dont know if ^ fix it or not, but I using newest version of advcanced_networkimage got some error on iOS (android is ok)

**Comment by mchome** [comment]
You can verify the version in `.packages` file at your project root folder.
I got `xxx/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_svg-0.10.3/lib/`.

**Comment by jinfagang** [comment]
@mchome I specific flutter_svg version to 0.10.3 now. 
![image](https://user-images.githubusercontent.com/21303438/53309420-9da34c80-38e2-11e9-9292-c94fc191fec6.png)
This better using 0.10.3 cause flutter_svg specific a version for now.

**Comment by mchome** [comment]
You dont need to do this. After performing `flutter packags upgrade`, you will get 0.10.3 because of `^` prefix.
