### ISSUE TITLE
conflict with flutter_svg-0.10.4

### ISSUE THREAD

**Issue by YaoShuwei** [mchome/flutter_advanced_networkimage#77]
Compiler message:
file:///C:/Users/yaosh/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_advanced_networkimage-0.4.9/lib/src/flutter_advanced_networksvg.dart:98:30: Error: The method 'AdvancedNetworkSvg.obtainKey' has fewer positional arguments than those of overridden method 'PictureProvider.obtainKey'.
  Future<AdvancedNetworkSvg> obtainKey() {
                             ^
file:///C:/Users/yaosh/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_svg-0.10.4/lib/src/picture_provider.dart:335:13: Context: This is the overridden method ('obtainKey').
  Future<T> obtainKey(PictureConfiguration picture);

**Comment by mchome** [comment]
Try commit `c0292f99275235499de2fe1b5d2705d69a8f7d3f` :)

**Comment by mchome** [comment]
`v0.4.11` released.
