### ISSUE TITLE
Another exception was thrown: FormatException: Invalid character (at character 6)

### ISSUE THREAD

**Issue by ChandraPrakashJangid** [mchome/flutter_advanced_networkimage#80]
For more info here is my question:

[Question detail](https://stackoverflow.com/questions/54959467/another-exception-was-thrown-formatexception-invalid-character-at-character-6)

**Comment by mchome** [comment]
Hmm, that's a bit weird. Is the stacktrace really related to your code snippet?

**Comment by ChandraPrakashJangid** [comment]
Yes that is related to my code.

**Comment by mchome** [comment]
Ok, have you try `Image.network`?

**Comment by ChandraPrakashJangid** [comment]
I did but my server is protected and needs header with token.

**Comment by mchome** [comment]
`Image.network` can add headers. Since i can't reproduce this issue, it's hard to help.

**Comment by ChandraPrakashJangid** [comment]
I found it is not generating due to this. Sorry guys.
