### ISSUE TITLE
Pleae do not raise exception on fail

### ISSUE THREAD

**Issue by carmas123** [mchome/flutter_advanced_networkimage#82]
Please can you disable (or parametrize) the throwing exception when image loading fail?
I set loadingWidget with starting image and I need to change it only if image is fully loaded.
Now if I don't set fallbackAssetImage or fallbackImage, an exception was raised.
I try to use fallbackAssetImage with same image, but we have a needless image loading from assets with a needless fading effect.

**Comment by mchome** [comment]
If you use `Image` with `AdvancedNetworkImage`, the exception was expected and i can not control this.
if you use `TransitionToImage` with  `AdvancedNetworkImage`, the exception was unexpected.
What actually happened in your code, can you post it out?

**Comment by carmas123** [comment]
I use TransitionToImage
The problem is that I don't want chage the loading placeholder if the remote image is not found.

**Comment by mchome** [comment]
You can set the same widget with `loadingWidget` and `placeholder`.

**Comment by carmas123** [comment]
Yes this is tru and now I do that :)
The problem is for the performance. The asstet is reloaded and the Fade animation show the same image.
We have an animation that hide and show the same image.

**Comment by mchome** [comment]
Well, did you really see the animation between `loadingWidget` and `placeholder`?

**Comment by carmas123** [comment]
Yes there is a fading animation between the images.

**Comment by mchome** [comment]
The animation only played when the image was loaded. There are no animation between `loadingWidget` and `placeholder`. Maybe you add animations to these widgets.

**Comment by carmas123** [comment]
No not from `placeholder` and `loadingwidget`.
The animation is executed from placeholder and failed widget!!

**Comment by mchome** [comment]
The `placeholder` is the failed widget. I don't understand your question, so post your code, your expected and which not work. Oh, and flutter version, package version.

**Comment by carmas123** [comment]
Ok, in the `flutter_advanced_networkimage.dart` from row 215 we have this:
`
    if (key.loadFailedCallback != null) key.loadFailedCallback();
    if (key.fallbackAssetImage != null) {
      ByteData imageData = await rootBundle.load(key.fallbackAssetImage);
      return await PaintingBinding.instance
          .instantiateImageCodec(imageData.buffer.asUint8List());
    }
    if (key.fallbackImage != null)
      return await PaintingBinding.instance
          .instantiateImageCodec(key.fallbackImage);

    **throw Exception('Failed to load $url.');**
`
In this method if `fallbackAssetImage` is null and `fallbackImage` is null an exception is raised.

My question is this: can we bypass this exception leaving the image as well as?

**Comment by mchome** [comment]
Answer is __NO__. But why, you have `TransitionToImage`, the error can be catched :/
This is the design of 0.4.x version, because flutter allow us to catch error and evict the bad `ImageStreamCompleter` after flutter 1.1.7.
