### ISSUE TITLE
Re-fetch/Re-paint issue with BoxDecoration

### ISSUE THREAD

**Issue by davbaron** [mchome/flutter_advanced_networkimage#92]
I think I have found a rather significant issue with re-fetching/re-painting of the advanced network image (ANI) when used as the image within a BoxDecoration. My app has numerous scrolling lists, with most having a 'leading' image (ANI). On one of those lists, I am using a delivered CircleAvatar. What I was seeing (using the Flutter Performance/Repaint Rainbow, etc...) was that the ANI is *constantly* fetching and re-painting its image. Upon digging into this, I found that the CircleAvatar is really just a Container with a BoxDecoration of BoxShape.circle. Regardless, I found that the ONLY time this issue occurs is when the ANI is used as the image of a DecorationImage, within a BoxDecoration, within a Container. I produced a sample page with only a single container on it - no lists, or scrolling, or anything.  When the image is set to an ANI, it goes crazy, constantly fetching/painting the image. If the image is set to a standard NetworkImage, there is a single fetch/paint. And, if the ANI is removed from the BoxDecoration, and instead is used as the Child of the Container, then there is only a single fetch/paint.

Here is the entire code that demonstrates this issue:
```dart
import 'package:flutter/material.dart';

import 'package:flutter_advanced_networkimage/provider.dart';

void main() {
  runApp(MaterialApp(
    title: 'Flutter Example',
    theme: ThemeData(primaryColor: Colors.blue),
    showPerformanceOverlay: true,
    home: TestPage(),
  ));
}

class TestPage extends StatefulWidget {
  @override
  _TestPageState createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  @override
  Widget build(BuildContext context) {
    ImageProvider avImg = AdvancedNetworkImage(
      "https://flutter.io/images/flutter-logo-sharing.png",
      retryLimit: 2,
      retryDuration: Duration(seconds: 5),
      disableMemoryCache: true,
      useDiskCache: true,
      loadedCallback: () {
        print('got photo');
      }, //here just for demonstration purposes
    );
    //avImg = new NetworkImage("https://flutter.io/images/flutter-logo-sharing.png");

    return MaterialApp(
      title: 'Re-paint/fetch Demo',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Re-paint/fetch Demo'),
        ),
        body: Center(
          child: Container(
            width: 100.0,
            height: 100.0,
            decoration: new BoxDecoration(
                image: new DecorationImage(
                  image: avImg,
                ),
                color: Colors.deepPurple,
                shape: BoxShape.circle,
                border: new Border.all(
                  color: Colors.deepPurple,
                  width: 0.5,
                )),
          ),
        ),
      ),
    );
  }
}
```
Please let me know if I am doing something wrong. Please note that in true practice (not this sample page) I use a FallbackAssetImage, as well as a RetryLimit (2) and a RetryDuration (5 secs). That is why you will see the additional options of DisableMemoryCache (true) and UseDiskCache (true). Both of those were put in on @mchome advice to overcome some other issue with multiple/different cached fallback images.  I have tried changing/removing these options just for this test - sometimes I get good results, but mostly not. I cannot find a pattern that always results in a single fetch/paint.

**Comment by mchome** [comment]
Hi, i wrote some comments in the source code before. I forgot to post that note to your original issue page, sorry. The `disableMemoryCache` is **not** recommended to use, because flutter will call (all kinds of) imageprovider a lot.
In your code, if you remove the `disableMemoryCache` option, the overlay will stop, it is the same as flutter's `NetworkImage`.

**Comment by davbaron** [comment]
That did the trick!  Thank you again for a great product.
