### ISSUE TITLE
precacheImage usage in pageview

### ISSUE THREAD

**Issue by abhee4** [mchome/flutter_advanced_networkimage#93]
@mchome, 
![Screenshot 2019-04-25 at 4 54 16 AM](https://user-images.githubusercontent.com/2958671/56700132-3b19d180-6716-11e9-8f83-8651b62d99db.png)
Can someone please let me know how to use precacheImage as a widget ?

**Comment by mchome** [comment]
Oh, you can run [precacheImage](https://docs.flutter.io/flutter/widgets/precacheImage.html) in `initState` or wrap it into a [Builder](https://docs.flutter.io/flutter/widgets/Builder-class.html) then return an empty [SizedBox](https://docs.flutter.io/flutter/widgets/SizedBox-class.html).

**Comment by abhee4** [comment]
Can you please show me an example?
I am completely noob for this and I am learning flutter via these kind of examples.

Thanks !!!

**Comment by mchome** [comment]
```dart
@override
void initState() {
  super.initState();
  precacheImage(
      AdvancedNetworkImage(
        mainMap.image,
        useDiskCache: true,
        fallbackAssetImage: 'assets/launch_image.png',
        cacheRule: CacheRule(
          storeDirectory: StoreDirectoryType.temporary,
          maxAge: const Duration(days: 7),
        ),
      ),
      context);
}
```
or
```dart
child: Builder(builder: (BuildContext context) {
  precacheImage(
      AdvancedNetworkImage(
        mainMap.image,
        useDiskCache: true,
        fallbackAssetImage: 'assets/launch_image.png',
        cacheRule: CacheRule(
          storeDirectory: StoreDirectoryType.temporary,
          maxAge: const Duration(days: 7),
        ),
      ),
      context);
  return SizedBox();
}),
```

**Comment by abhee4** [comment]
@mchome,  Thanks so much for the support, I would use it and will let you know how it fared?
I was also thinking if this would hit the overall performance of the app if my app is fetching a considerable amount of data from json, say 50 images in a fetch. What do you think ?

**Comment by abhee4** [comment]
Also, how precaching works ? Is it storing the data to the disk and would not make a network call to fetch these images or so my understanding is wrong ?

**Comment by mchome** [comment]
Flutter has [ImageCache](https://docs.flutter.io/flutter/painting/ImageCache-class.html) as memory cache. 
> I was also thinking if this would hit the overall performance of the app if my app is fetching a considerable amount of data from json, say 50 images in a fetch.

You can pick up [compute](https://docs.flutter.io/flutter/foundation/compute.html) function if you feel laggy.

> Is it storing the data to the disk and would not make a network call to fetch these images or my understanding is wrong ?

Flutter's precache function can help you to grab the images to memory. The imageprovider is trying to get the image from network or disk.

**Comment by abhee4** [comment]
> ```dart
> child: Builder(builder: (BuildContext context) {
>   precacheImage(
>       AdvancedNetworkImage(
>         mainMap.image,
>         useDiskCache: true,
>         fallbackAssetImage: 'assets/launch_image.png',
>         cacheRule: CacheRule(
>           storeDirectory: StoreDirectoryType.temporary,
>           maxAge: const Duration(days: 7),
>         ),
>       ),
>       context);
>   return SizedBox();
> }),
> ```

I used it here, and it does not show any image, just a grey box:::

               child: Stack(
                         children: <Widget>[
                              Container(
                                width: 1080.0,
                                height: 1920.0,
                                child: Builder(builder: (BuildContext context) {
                                  precacheImage(
                                      AdvancedNetworkImage(
                                        mainMap.image,
                                        useDiskCache: true,
                                        fallbackAssetImage:
                                            'assets/launch_image.png',
                                        cacheRule: CacheRule(
                                          storeDirectory:
                                              StoreDirectoryType.temporary,
                                          maxAge: const Duration(days: 7),
                                        ),
                                      ),
                                      context);
                                  return SizedBox();
                                }),
                              ),

Do you have any idea ?

> ```dart
> @override
> void initState() {
>   super.initState();
>   precacheImage(
>       AdvancedNetworkImage(
>         mainMap.image,
>         useDiskCache: true,
>         fallbackAssetImage: 'assets/launch_image.png',
>         cacheRule: CacheRule(
>           storeDirectory: StoreDirectoryType.temporary,
>           maxAge: const Duration(days: 7),
>         ),
>       ),
>       context);
> }
> ```
![Screenshot 2019-04-26 at 5 29 26 AM](https://user-images.githubusercontent.com/2958671/56775303-260b7400-67e4-11e9-8e1f-ef25d5df7d12.png)

This one is not possible for me as I am fetching json data for image below the initState and initState do not find it !!!!

Please help !!!!

**Comment by mchome** [comment]
If you need to display image, just see https://github.com/mchome/flutter_advanced_networkimage/tree/master/example.

**Comment by abhee4** [comment]
Hi again @mchome,

Thanks for the link, but I checked that already, it doesn't show any precache example.
The one mentioned by you doesn't work as expected.

What else can I use instead of SizedBox() ?

Using Image results in error.

**Comment by mchome** [comment]
precacheImage does not display anything because it is not a widget. If you want to display images, you have to use `Image` or `TransitionToImage`.
What are you expecting?

**Comment by abhee4** [comment]
I am using it here : https://github.com/abhee4/testproj.git

Please run this few lines project and see the outcome. Now, all i want to do, is to reproduce the same with precache.

I have put comment in the lines for better understanding.

**Comment by mchome** [comment]
Oh, you want to precache in pageview, this is quite easy.
```dart
  // hope this can help you
  @override
  Widget build(BuildContext context) {
    super.build(context);

    return Stack(
      children: <Widget>[
        FutureBuilder<List>(
          builder: (BuildContext context, AsyncSnapshot<List> snapshot) {
            if (snapshot.data == null) {
              return Center(child: CircularProgressIndicator());
            } else {
              List<Items> items = snapshot.data;

              return PageView.builder(
                itemCount: items.length,
                itemBuilder: (BuildContext context, int index) {
                  Items mainMap = items[index];

                  for (var i = 0; i < 5; i++) {
                    var _i = (index + i).clamp(0, items.length - 1);
                    // print(_i); // print precache index
                    precacheImage(
                      AdvancedNetworkImage(
                        items[_i].enclosure.link,
                        useDiskCache: true,
                        fallbackAssetImage: 'assets/launch_image.png',
                        cacheRule: CacheRule(
                          storeDirectory: StoreDirectoryType.temporary,
                          maxAge: const Duration(days: 7),
                        ),
                      ),
                      context,
                    );
                  }

                  return Material(
                    color: Colors.grey,
                    child: Stack(
                      children: <Widget>[
                        Container(
                          width: 800.0,
                          height: 1000.0,
                          child: TransitionToImage(
                            image: AdvancedNetworkImage(
                              mainMap.enclosure.link,
                              useDiskCache: true,
                              fallbackAssetImage: 'assets/launch_image.png',
                              cacheRule: CacheRule(
                                storeDirectory: StoreDirectoryType.temporary,
                                maxAge: const Duration(days: 7),
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  );
                },
              );
            }
          },
          future: _future,
        ),
      ],
    );
  }
```

**Comment by abhee4** [comment]
Thanks for all the help so far !

TransitionToImage is showing error that, it is not defined for _MainPageviewScreenState.

Do I need to get some library or something, i thought it to be the part of this package. ?

**Comment by mchome** [comment]
Please update your code.

**Comment by mchome** [comment]
Try to make flutter's cachesize bigger in `ImageCache.maximumSizeBytes`.
