### ISSUE TITLE
SliverList show the previous image, while new image is downloading

### ISSUE THREAD

**Issue by basketball-ico** [mchome/flutter_advanced_networkimage#95]
Hello I have a SliverList with items that have
```dart
TransitionToImage(
      image: AdvancedNetworkImage(
        widget.url,
        useDiskCache: true,
        fallbackAssetImage: 'assets/images/fail.png',
      ),
      loadingWidget: Container(
        height: 400,
        child: Center(
          child: CircularProgressIndicator(),
        ),
      ),
      disableMemoryCacheIfFailed: true,
    );
```
but when I add new item to the list, the new item is added in the position 0 of the list, and while the image is downloading it show the image of the previous item that was in this position and not the loading widget, when the image is downloaded it show correct, but i want to avoid to show the previous image two times.

Thanks

**Comment by mchome** [comment]
Full example please.

**Comment by basketball-ico** [comment]
Hello I create a sample [here](https://gist.github.com/basketball-ico/da083bceece8ad408a55d668c633eb98),

the only dependencies is 
```dart
  flutter_advanced_networkimage: ^0.5.0-alpha.1
```

Is a Listview with images,
1. please don't scroll
2. Press the floating button to load 1 more image
3. press the floating button multiple times, after some images are loaded, you will see that the first item show the previous image, and when are downloading it show the correct image.

thanks @mchome

**Comment by basketball-ico** [comment]
@mchome hi, I'm sorry for bothering you, have you already checked it?
thank you 🤗

**Comment by mchome** [comment]
Try adding key to listview builder like this: https://stackoverflow.com/questions/51279611/flutter-listview-builder-not-updating-after-insert :)

**Comment by basketball-ico** [comment]
@mchome thanks, that works :D
