### ISSUE TITLE
How to reload image when fail

### ISSUE THREAD

**Issue by basketball-ico** [mchome/flutter_advanced_networkimage#96]
I have an image in one screen, if the image failed to load it show a fallBackImage,
Then i pop this screen and the push again this screen, but the image is show again the fallBackImage without try to download again.

Also I have a list of image, if don't have internet and some images show fallBackImage, how can i reload this images ?

this is my image
```dart
TransitionToImage(
      image: AdvancedNetworkImage(
        widget.url,
        useDiskCache: true,
        fallbackAssetImage: 'assets/images/fail.png',
      ),
      loadingWidget: Container(
        height: 400,
        child: Center(
          child: CircularProgressIndicator(),
        ),
      ),
      disableMemoryCacheIfFailed: true,
    );
```

thanks

**Comment by mchome** [comment]
You shold use placeholder in TransitionToImage, not fallbackAssetImage in AdvancedNetworkImage.

**Comment by basketball-ico** [comment]
@mchome hello
when I not use fallBackAssetImage, flutter throw exception in this line

```dart
// flutter_advanced_networkimage.dart
....
    if (key.fallbackImage != null)
      return await PaintingBinding.instance
          .instantiateImageCodec(key.fallbackImage);
    // Line 204
    throw Exception('Failed to load $url.');
```

but I compare this with the repository file and don't see this throw [this line](https://github.com/mchome/flutter_advanced_networkimage/blob/4af0f14aa32df6fa2238f4f8bf279b867e338167/lib/src/provider/flutter_advanced_networkimage.dart#L204) I use `^0.4.15`

**Comment by mchome** [comment]
Use 0.5.0-alpha.1 and try again.
